
// Objective-C API for talking to the following Go packages
//
//	github.com/example/go-react-native-backend
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Gobridge_FRAMEWORK_H__
#define __Gobridge_FRAMEWORK_H__

#include "Gobridge.objc.h"
#include "Universe.objc.h"

#endif
