name: Build Android

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: mobile-app/package-lock.json

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
          cache-dependency-path: backend/go.sum

      - name: Setup Go backend environment
        working-directory: backend
        run: make setup

      - name: Build Go backend for Android
        working-directory: backend
        run: make android

      - name: Install Node dependencies
        working-directory: mobile-app
        run: npm install

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Grant execute permission for gradlew
        run: chmod +x mobile-app/android/gradlew

      - name: Build Release APK
        working-directory: mobile-app/android
        env:
          NODE_ENV: production
          EXPO_USE_FAST_RESOLVER: 1
        run: |
          ./gradlew assembleRelease \
            --no-daemon \
            --parallel \
            --build-cache \
            -Dorg.gradle.jvmargs="-Xmx5g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError" \
            -Dkotlin.compiler.execution.strategy=in-process

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: mobile-app/android/app/build/outputs/apk/release/app-release.apk
          retention-days: 7

      - name: Stop Gradle daemon
        if: always()
        working-directory: mobile-app/android
        run: ./gradlew --stop
