name: Build iOS

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS App
    runs-on: [self-hosted, macOS, ARM64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Go backend for iOS
        run: nix develop --command bash -c 'make -C backend setup && make -C backend test && make -C backend vet && make -C backend ios'

      - name: Clean iOS build cache
        run: rm -rf mobile-app/ios/build mobile-app/ios/Pods

      - name: Build iOS Simulator App
        run: nix develop --command bash -c 'make -C mobile-app ios'

      - name: Prepare iOS app for upload
        working-directory: mobile-app/ios/build/Build/Products/Release-iphonesimulator
        run: cp -r mobileapp.app rn-golang-ios.app

      - name: Upload Simulator Build
        uses: actions/upload-artifact@v4
        with:
          name: rn-golang-ios.app
          path: mobile-app/ios/build/Build/Products/Release-iphonesimulator/rn-golang-ios.app
          retention-days: 60
